on: push

jobs:
 upstream_actions:
    name: upstream_actions
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
          aws-region: eu-west-1
      - run: aws sts get-caller-identity
      - run: aws s3 ls

 forked_action_access_denied:
   name: forked_action_access_denied
   permissions:
     id-token: write
     contents: write
   runs-on: ubuntu-latest
   steps:
     - name: Configure AWS Credentials
       uses: dimitar-hristov/configure-aws-credentials@0.0.3
       with:
         role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
         aws-region: eu-west-1
         inline-session-policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:GetBucketLocation\",\"Resource\":\"*\"}]}"
     - run: aws sts get-caller-identity
     - run: aws s3 ls

 forked_action_with_enough_permissions:
   name: forked_action_with_enough_permissions
   permissions:
     id-token: write
     contents: write
   runs-on: ubuntu-latest
   steps:
     - name: Configure AWS Credentials again
       uses: dimitar-hristov/configure-aws-credentials@0.0.3
       with:
         role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
         aws-region: eu-west-1
         inline-session-policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:List*\",\"Resource\":\"*\"}]}"
     - run: aws sts get-caller-identity
     - run: aws s3 ls
