on: push

jobs:
 see_url:
    name: see_url
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          export AWS_ROLE_ARN=arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=eu-west-1

          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          aws sts get-caller-identity

 upstream_actions:
    name: upstream_actions
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
          aws-region: eu-west-1
      - run: aws sts get-caller-identity
#      - run: aws s3 ls

#  forked_action_access_denied:
#    name: forked_action_access_denied
#    permissions:
#      id-token: write
#      contents: write
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure AWS Credentials
#        uses: dimitar-hristov/configure-aws-credentials@0.0.3
#        with:
#          role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
#          aws-region: eu-west-1
#          inline-session-policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:GetBucketLocation\",\"Resource\":\"*\"}]}"
#      - run: aws sts get-caller-identity
#      - run: aws s3 ls

#  forked_action_with_enough_permissions:
#    name: forked_action_with_enough_permissions
#    permissions:
#      id-token: write
#      contents: write
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure AWS Credentials again
#        uses: dimitar-hristov/configure-aws-credentials@0.0.3
#        with:
#          role-to-assume: arn:aws:iam::${{secrets.account}}:role/GitHubActionsOidcRole
#          aws-region: eu-west-1
#          inline-session-policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:List*\",\"Resource\":\"*\"}]}"
#      - run: aws sts get-caller-identity
#      - run: aws s3 ls
